# Generated by Django 4.2.6 on 2023-10-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=2000)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('keywords', models.CharField(choices=[('sustainibility', 'SUSTAINIBILITY'), ('car', 'CAR'), ('buildings', 'BUILDINGS'), ('recycling', 'RECYCLING'), ('materials', 'MATERIALS')], default='Choose', max_length=14)),
                ('methods', models.CharField(choices=[('lca', 'Life Cycle Assessment'), ('eemrio', 'Environmentally Extended Multi-Regional Input-Output analysis'), ('ia', 'Impact Assessment'), ('mfa', 'Material Flow Analysis')], default='Choose', max_length=6)),
            ],
        ),
    ]
