# Generated by Django 4.2.6 on 2023-11-13 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_teaching", "0007_alter_personcourse_course_alter_personcourse_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personcourse",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personcourse_course",
                to="app_teaching.course",
            ),
        ),
    ]
