# Generated by Django 4.2.6 on 2023-11-16 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_teaching", "0010_alter_personcourse_course_alter_personcourse_person"),
    ]

    operations = [
        migrations.CreateModel(
            name="Position_Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Instituttleder", "Instituttleder"),
                            ("Nestleder forskning", "Nestleder forskning"),
                            ("Nestleder utdanning", "Nestleder utdanning"),
                            ("Faggruppeleder", "Faggruppeleder"),
                            ("Studieprogramleder", "Studieprogramleder"),
                            (
                                "Leder - forskningsprosjekt",
                                "Leder - forskningsprosjekt",
                            ),
                            (
                                "WP leder - Forskningsprosjekt",
                                "WP leder - Forskningsprosjekt",
                            ),
                            ("Leder - EU prosjekt", "Leder - EU prosjekt"),
                            ("WP leder - EU prosjekt", "WP leder - EU prosjekt"),
                            ("Antall PhD studenter", "Antall PhD studenter"),
                        ],
                        default="-",
                        max_length=40,
                    ),
                ),
                (
                    "emne",
                    models.CharField(
                        choices=[("L", "L"), ("P", "P")], default="-", max_length=2
                    ),
                ),
                (
                    "antall_time",
                    models.IntegerField(
                        choices=[("50", "50"), ("70", "70"), ("100", "100")],
                        default="-",
                        max_length=3,
                    ),
                ),
                (
                    "arsverk",
                    models.IntegerField(
                        choices=[("20", "20"), ("80", "80")], default="-", max_length=3
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PersonPosition_Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_teaching.position_activity",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_teaching.person",
                    ),
                ),
            ],
        ),
    ]
