# Generated by Django 4.2.6 on 2023-11-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_teaching", "0011_position_activity_personposition_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position_activity",
            name="antall_time",
            field=models.IntegerField(
                choices=[("50", "50"), ("70", "70"), ("100", "100")], default="-"
            ),
        ),
        migrations.AlterField(
            model_name="position_activity",
            name="arsverk",
            field=models.IntegerField(
                choices=[("20", "20"), ("80", "80")], default="-"
            ),
        ),
    ]
