# Generated by Django 4.2.6 on 2023-11-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_teaching", "0012_alter_position_activity_antall_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position_activity",
            name="antall_time",
            field=models.IntegerField(
                choices=[("50", "50"), ("70", "70"), ("100", "100")],
                default="-",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="position_activity",
            name="arsverk",
            field=models.IntegerField(
                choices=[("20", "20"), ("80", "80")], default="-", null=True
            ),
        ),
    ]
