# Generated by Django 4.2.6 on 2023-11-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_teaching", "0013_alter_position_activity_antall_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position_activity",
            name="antall_time",
            field=models.CharField(
                blank=True,
                choices=[("50", "50"), ("70", "70"), ("100", "100")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="position_activity",
            name="arsverk",
            field=models.CharField(
                blank=True,
                choices=[("20", "20"), ("80", "80")],
                max_length=3,
                null=True,
            ),
        ),
    ]
