# Generated by Django 4.2.6 on 2023-11-20 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_teaching", "0014_alter_position_activity_antall_time_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PersonPosition_Activity",
        ),
        migrations.DeleteModel(
            name="Position_Activity",
        ),
    ]
