# Generated by Django 4.2.6 on 2023-12-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_teaching", "0019_alter_personactivity_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="courses",
            field=models.ManyToManyField(
                null=True, related_name="courses", to="app_teaching.course"
            ),
        ),
    ]
