# Generated by Django 5.0 on 2024-04-19 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_teaching", "0021_user"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
